version: "3"

services: 
        nginx:
                container_name: nginx
                build: ./requirements/nginx/
                image: nginx
                ports:
                    - 443:443
                restart: on-failure
                networks:
                        - Inception
                volumes:
                        - wordpress:/var/www/html
        mariadb:
                 container_name: mariadb
                 build: requirements/mariadb/
                 expose:
                     - 3306
                 env_file: .env
                 restart: on-failure
                 networks:
                     - Inception
         
networks:
        Inception:
  
volumes:
        wordpress:
                name: "wordpress"
                driver: local
                driver_opts:
                        type: none
                        o: bind
                        device: /home/jofernan/data/wordpress
        mariadb:
                name: "mariadb"
                driver: local
                driver_opts:
                        type: none
                        o: bind
                        device: /home/jofernan/data/mariadb


                
